[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tools"
authors = [
    {name = "Manuel Garcia", email = "manu@own.edu"},
]
description = "My package description"
readme = "README.rst"
requires-python = ">=3.10"
keywords = ["one", "two"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Framework :: PDF",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "PyPDF2", 
    "PyMuPDF",
    'importlib-metadata; python_version<"3.8"',
]
dynamic = ["version"]

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]