dir:
  input: data-pipelines/data/design-data100/
  output: data-pipelines/data/layout-ocr-test/
  temp: data-pipelines/data/tmp/
entry: '00001'
layout:
  caption_settings:
    offset: [4, "mm"]
    direction: down
    keywords: ['figure', 'caption', 'figuur']
  image_settings:
    width: 100
    height: 100
ocr:
  resolution: 200
  caption_settings:
    offset: [10, "px"]
    direction: down
    keywords: ['figure', 'caption', 'figuur']

